# Generated by Django 3.1.3 on 2024-11-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDiary', '0003_diary_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diaryfolder',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_folder_per_user'),
        ),
    ]
