# Generated by Django 3.1.3 on 2024-11-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDiary', '0004_auto_20241121_0041'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('title', 'folder'), name='unique_diary_title_per_folder'),
        ),
    ]
